---
- name: provision EC2 instance on AWS
  hosts: localhost

  vars:
    id: "web-app"
    region: "us-east-1"
    
  tasks:
  - name: import vars from result_sec_group.json
    include_vars:
      file: /var/tmp/result_sec_group.json
      name: result_sec_group

  - name: provision EC2 instance
    ec2:
      key_name: datadog
      id: "{{ id }}"
      instance_type: t2.micro
      image: ami-0c2b8ca1dad447f8a
      region: "{{ region }}"
      vpc_subnet_id: subnet-ef19dfa7
      wait: yes
      count: 1
      group_id: "{{ result_sec_group.group_id }}"
      instance_tags:
        Name: "mywebserver"
    register: ec2