---
- name: Play to install and start Apache Server
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: install apache 
    yum :
      name: httpd 
      state: present

  - name: start apache
    service: 
      name: httpd 
      state: started 
      enabled: yes