---
- name: Play to create EC2 resources and finally a RHEL8 instance. 
  hosts: localhost
  vars:
    aws_region: 
  tasks:
    - name: Task to create the VPC
      ec2_vpc_net:
        name: ansible_awx_vpc
        cidr_block: 
        region: "{{ aws_region }}"
        tenancy: default
      register: ansible_awx_vpc

    - name: Create an Internet Gateway and associate to the VPC
      ec2_vpc_igw:
        vpc_id: "{{ ansible_awx_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
      register: ansible_awx_igw

    - name: Create a subnet in the VPC
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ ansible_awx_vpc.vpc.id }}"
        cidr: 
        region: "{{ aws_region }}"
      register: ansible_awx_subnet

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ ansible_awx_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        subnets:
          - "{{ ansible_awx_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ ansible_awx_igw.gateway.id }}"
    
    - name: Task to create AWS Security Groups
      ec2_group:
        name: ansible_awx_sg
        description: AWS Security Group for AWX Demonstration
        vpc_id: "{{ ansible_awx_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports: 
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all connections on port 22

    - name: Task to provision the RHEL8 EC2 instance
      ec2:
        region: "{{ aws_region }}"
        key_name: 
        instance_type: t2.medium
        image:
        wait: yes
        group:
        count: 1
        vpc_subnet_id: "{{ ansible_awx_subnet.subnet.id }}"
        assign_public_ip: yes
      register: ansible_awx_instance

      - name: Show RHEL8 instance details
        debug:
          msg: "The RHEL8 instance is accessible at {{ ansible_tower_instance.instances[0].public_ip }}"

